### ISSUE TITLE
Not able to attach an address to the tangle!

### ISSUE THREAD

**Issue by utkarsh009** [MichaelSchwab/iota-commandline-wallet#7]
- When the node was set to `http://node01.iotatoken.nl:14265`:
```
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js ShowDB
INDEX: 0 ADR: RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWXRVNIJRJFD Balance: 0 Status: published
INDEX: 1 ADR: PCNDVBQXCGWDHLQQMXIRNQNVILKXRXUAKK9YBMLIEMA9ZVCUHZWTGWEWACODBYUWRFAFQADJBUMLNQMOBUVGASMWRB Balance: 0 Status: published
INDEX: 2 ADR: MFDWRYMJZB9IOWMJZNQJ9KJTALYJIZBNLMCHPRZMI9ZZVZZAUDHMZTUKEQAJLNSPYFVZLTV9RQSFNTTTCTKJLKOTEC Balance: 0 Status: published
INDEX: 3 ADR: JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA Balance: 0 Status: published
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Sync
INDEX: 0 ADR: RRUZHOTCLWFKVHFNKXME.... Balance: 0 Status: published
INDEX: 1 ADR: PCNDVBQXCGWDHLQQMXIR.... Balance: 0 Status: published
INDEX: 2 ADR: MFDWRYMJZB9IOWMJZNQJ.... Balance: 0 Status: published
INDEX: 3 ADR: JPWZWLUPMXWAWZPNTMND.... Balance: 0 Status: published
INDEX: 4 ADR: TAOUABJUYTXCNKCSVEHQ.... Balance: 0 Status: new
INDEX: 5 ADR: CQRBWCHUSQQWFHIKBJWU.... Balance: 0 Status: new
INDEX: 6 ADR: BQDU9EBAO9GDFFVBYKKI.... Balance: 0 Status: new
INDEX: 7 ADR: TUIEWQHUOPYSXJFOY9YC.... Balance: 0 Status: new
INDEX: 8 ADR: GFKAMUJMLXRKWPMNKKTQ.... Balance: 0 Status: new
INDEX: 9 ADR: ULSKENXEXNEQXWOEKUNK.... Balance: 0 Status: new
INDEX: 10 ADR: WHGQISFLCYVPGJLBVSRD.... Balance: 0 Status: new
INDEX: 11 ADR: SUVOUMXTASLNFJPVYG9C.... Balance: 0 Status: new
INDEX: 12 ADR: LMYMCKWZZQTYTNHQEDOG.... Balance: 0 Status: new
INDEX: 13 ADR: OUNTAOVSGYISYIFALIGV.... Balance: 0 Status: new
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA
{"replayedBundles":[],"status":"ok"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Transfer JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA 0
{ status: "error", message: "Transfer failed. Request Error: COMMAND attachToTangle is not available on this node"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA
{"replayedBundles":[],"status":"ok"}
```
- When the node was set to `http://iota.bitfinex.com:80`:
```
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Transfer JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA 0
{ status: "error", message: "Transfer failed. Invalid Response: I'm depressed, leave me be.
"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWXRVNIJRJFD
(node:1893) UnhandledPromiseRejectionWarning: Error: Invalid Response: I'm depressed, leave me be.

    at Object.invalidResponse (/extra/iota-commandline-wallet/node_modules/iota.lib.js/lib/errors/requestErrors.js:5:12)
    at makeRequest.prepareResult (/extra/iota-commandline-wallet/node_modules/iota.lib.js/lib/utils/makeRequest.js:283:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/extra/iota-commandline-wallet/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/extra/iota-commandline-wallet/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/extra/iota-commandline-wallet/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/extra/iota-commandline-wallet/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:1893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1893) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
- When the node was set to `http://eugene.iotasupport.com:14999`:
```
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWXRVNIJRJFD
BUNDLE: GZZZJGECECQ9OBVOCIRGICBDVYH9LZKGGSUXECUCVXHXJWWDOICADKQMWZDJCFNVJJEUHRFKKKLGIIPZZ
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 1 TAIL: G9DAPGSUKEFRTOJAYTOMXSEXATSJLRUUEXTXCFSPSONAXQHYLNRYPSKJIPTJGWGOXVKQDNIJXNGVZ9999 Funding: true
Replaying
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 1 TAIL: G9DAPGSUKEFRTOJAYTOMXSEXATSJLRUUEXTXCFSPSONAXQHYLNRYPSKJIPTJGWGOXVKQDNIJXNGVZ9999 Funding: true
{ status: "error", message: "Replay failed. Request Error: COMMAND attachToTangle is not available on this node"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Transfer JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA 0
{ status: "error", message: "Transfer failed. Request Error: COMMAND attachToTangle is not available on this node"}
```
Looks like none of the nodes are letting me attach the addresses to the tangle!

**Comment by MichaelSchwab** [comment]
See this Issue : https://github.com/MichaelSchwab/iota-commandline-wallet/issues/6

**Comment by utkarsh009** [comment]
@MichaelSchwab I have created a GUI for this wallet. Would you like to test it? You can find it right [here](https://github.com/utkarsh009/heliota). Any suggestions or fixes are appreciated. Please let people, who are interested in a GUI, know about it. Cheers!
